changes made for czentrix
PSMRI/HelplineMCTS-API pull request #7
Opened 2023-08-09 09:49 UTC by Vidyaaa24

2023-08-09 10:42 UTC, harimohanr commented on src/main/java/com/iemr/mcts/data/agent/MctsOutboundCallDetail.java
> +	private String callCentreID;
@Vidyaaa24 This property naming is wrong. It is not callCentreID. It should be callId

2023-08-09 10:43 UTC, harimohanr commented on src/main/java/com/iemr/mcts/data/agent/MctsOutboundCallDetail.java
> +	public MctsOutboundCallDetail(Long callDetailID, String outboundCallType, String callCentreID,
@Vidyaaa24 It should be callId

2023-08-09 10:43 UTC, harimohanr commented on src/main/java/com/iemr/mcts/data/agent/MctsOutboundCallDetail.java
> +		this.callCentreID = callCentreID;
@Vidyaaa24 it should be callId

2023-08-09 10:44 UTC, harimohanr requested changes
@Vidyaaa24 Please change the callCentreId to callId

2023-08-10 05:39 UTC, Anjana2310 requested changes
@Vidyaaa24 please modify callCentreID  to callId in all its references

2023-08-11 05:25 UTC, Anjana2310 approved these changes
@Vidyaaa24 Looks good to me

2023-08-11 05:33 UTC, harimohanr approved these changes
@Vidyaaa24 Looks okay to me

2023-08-11 05:33 UTC, merged